# Cluster and Cloud Computing 2023
# Assignment 2
# Team 46

# Kunal Patel : 1291822
# Mayank Yadav : 1403092
# Harsh Mangla : 1418017
# Sophie von Doussa : 1064884
# Maxson Stephen Mathew : 1428525

# City : Melbourne
---
- name: Remove a container with same name if exists
  community.docker.docker_container:
    name: "{{ server_name }}_container"
    state: absent